# Atividade #5

## REGRESS√ÉO LINEAR USANDO PYTHON

### Importando as bibliotecas

In [43]:
# Importa√ß√£o de Bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
import warnings
warnings.filterwarnings('ignore')

### Lendo o arquivo

In [5]:
# leitura de dados (CSV), separados por ponto e v√≠rgula no nosso caso
df = pd.read_csv('house.csv',';')
df

   houseSize  lotSize  bedrooms  granite  bathroom  sellingPrice
0       3529     9191         6        0         0        205000
1       3247    10061         5        1         1        224900
2       4032    10150         5        0         1        197900
3       2397    14156         4        1         0        189900
4       2200     9600         4        0         1        195000
5       3536    19994         6        1         1        325000
6       2983     9365         5        0         1        230000

### Separando dados de Treinamento (70%) e Testes (30%)

In [37]:
# separa a coluna target (colunas com os dados das classes)
y = 'sellingPrice'

# separa as colunas de features (colunas com os dados)
x = df.drop(columns=['sellingPrice'])

y = df[y]

print("X: \n", x)
print("Y: \n", y)

X:
    houseSize  lotSize  bedrooms  granite  bathroom
0       3529     9191         6        0         0
1       3247    10061         5        1         1
2       4032    10150         5        0         1
3       2397    14156         4        1         0
4       2200     9600         4        0         1
5       3536    19994         6        1         1
6       2983     9365         5        0         1
Y:
 0    205000
1    224900
2    197900
3    189900
4    195000
5    325000
6    230000
Name: sellingPrice, dtype: int64

In [13]:
# Uso do Modelo para fazer Classifica√ß√µes com os dados de Testes
# Para funcionar, deve ser importada a biblioteca:
from sklearn.model_selection import train_test_split

In [19]:
# Separa√ß√£o de dados para Treinamento (train) e Testes (test); Vari√°veis X s√£o as colunas features e Vari√°veis Y trata-se da coluna target
Xtrain, Xval, Ytrain, Yval = train_test_split(x, y, test_size=0.3, random_state=0)

In [20]:
# Visualiza√ß√£o dos dados de Treinamento e Testes, j√° separados
Xtrain
Xval

   houseSize  lotSize  bedrooms  granite  bathroom
6       2983     9365         5        0         1
2       4032    10150         5        0         1
1       3247    10061         5        1         1

### Regress√£o Linear

In [30]:
# Cria√ß√£o do modelo de Regress√£o linear
model = LinearRegression()

In [33]:
# Treino do modelo com os Dados
model.fit(Xtrain, Ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

#### Coeficiente de Determina√ß√£o R2

In [34]:
# C√°lculo do Coeficiente de Determina√ß√£o R2 (quanto mais pr√≥ximo de 1, melhor o modelo!)
r_sq = model.score(Xtrain, Ytrain) 
print('Coefficient of determination:', r_sq)

Coefficient of determination: 1.0

#### C√°lculo de MSE (Mean Squared Error)

In [35]:
# C√°lculo de MSE (Mean Squared Error)
np.mean((model.predict(Xval)-Yval)**2)

1108340796.4604137

#### Regress√£o Linear: ùëì(ùë•) = ùëè‚ÇÄ + ùëè‚ÇÅùë•

In [36]:
# Admitindo a Equa√ß√£o da Regress√£o Linear: ùëì(ùë•) = ùëè‚ÇÄ + ùëè‚ÇÅùë•
print('b0 ou intercept:', model.intercept_)
print('b1 ou coeficiente (slope):', model.coef_)

b0 ou intercept: -17986.476495571434
b1 ou coeficiente (slope): [ 2.51367438e+01  9.24595053e+00  8.21656269e+03 -1.61182250e+04
  3.60582642e+04]